title: Chandler Swift's Blog
plugins:
    - jekyll-paginate
    - jekyll-seo-tag
markdown: kramdown
paginate: 10
paginate_path: "/archive/page:num/"
include:
    - .well-known
exclude:
    - _drafts/personal
collections:
    projects:
        output: true
