title: Chandler Swift's Blog
baseURL: https://chandlerswift.com/

pygmentsUseClasses: true

ignoreFiles:
  - drafts/personal

permalinks:
  posts: /:year/:month/:day/:slug

uglyURLs: true
disablePathToLower: true

markup:
  goldmark:
    renderer:
      unsafe: true

frontmatter:
  date:
    - :filename
    - :default
    - :fileModTime
  lastmod:
    - lastmod
    - :fileModTime
    - :default
